modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "servein"
version = "${version}"
displayName = "SerVein"
authors = "Brittank88"
description = '''
A server-side-only vein miner implementation!
'''
logoFile = "assets/servein/icon.png"

[[dependencies.servein]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.servein]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.servein]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "SERVER"